services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - wowspelldle-network

networks:
  wowspelldle-network:
    driver: bridge