services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - wowspelldle-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    networks:
      - wowspelldle-network

networks:
  wowspelldle-network:
    driver: bridge